hostname: {{.DEFAULT_HOSTNAME}}
k3os:
  defaults:
    modules:
    - br_netfilter
    - overlay
  upgrade:
    url: {{.K3OS_RELEASES_YML}}/releases{{.SUFFIX}}.yaml
    policy: download
  sysctl:
    fs.file-max: 1000000000
